// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: mcp/grpc/v1/transport.proto

package mcpgrpcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MCPTransport_Connect_FullMethodName = "/mcp.grpc.v1.MCPTransport/Connect"
)

// MCPTransportClient is the client API for MCPTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MCPTransport carries MCP JSON-RPC traffic over a single gRPC bidirectional
// stream. It is a transport, not a typed MCP API: the payload is an opaque
// JSON-RPC message (see Frame). One Connect call == one MCP session.
type MCPTransportClient interface {
	// Connect opens a logical bidirectional JSON-RPC connection. Each call is a
	// distinct MCP session; the call lives for the duration of that session.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
}

type mCPTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPTransportClient(cc grpc.ClientConnInterface) MCPTransportClient {
	return &mCPTransportClient{cc}
}

func (c *mCPTransportClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MCPTransport_ServiceDesc.Streams[0], MCPTransport_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MCPTransport_ConnectClient = grpc.BidiStreamingClient[Frame, Frame]

// MCPTransportServer is the server API for MCPTransport service.
// All implementations must embed UnimplementedMCPTransportServer
// for forward compatibility.
//
// MCPTransport carries MCP JSON-RPC traffic over a single gRPC bidirectional
// stream. It is a transport, not a typed MCP API: the payload is an opaque
// JSON-RPC message (see Frame). One Connect call == one MCP session.
type MCPTransportServer interface {
	// Connect opens a logical bidirectional JSON-RPC connection. Each call is a
	// distinct MCP session; the call lives for the duration of that session.
	Connect(grpc.BidiStreamingServer[Frame, Frame]) error
	mustEmbedUnimplementedMCPTransportServer()
}

// UnimplementedMCPTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCPTransportServer struct{}

func (UnimplementedMCPTransportServer) Connect(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMCPTransportServer) mustEmbedUnimplementedMCPTransportServer() {}
func (UnimplementedMCPTransportServer) testEmbeddedByValue()                      {}

// UnsafeMCPTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPTransportServer will
// result in compilation errors.
type UnsafeMCPTransportServer interface {
	mustEmbedUnimplementedMCPTransportServer()
}

func RegisterMCPTransportServer(s grpc.ServiceRegistrar, srv MCPTransportServer) {
	// If the following call panics, it indicates UnimplementedMCPTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCPTransport_ServiceDesc, srv)
}

func _MCPTransport_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MCPTransportServer).Connect(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MCPTransport_ConnectServer = grpc.BidiStreamingServer[Frame, Frame]

// MCPTransport_ServiceDesc is the grpc.ServiceDesc for MCPTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCPTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcp.grpc.v1.MCPTransport",
	HandlerType: (*MCPTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _MCPTransport_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mcp/grpc/v1/transport.proto",
}
