// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mcp/grpc/v1/transport.proto

package mcpgrpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame is a pure envelope around a single encoded JSON-RPC message. Session
// id, auth tokens and trace context belong in gRPC metadata (headers) plus
// interceptors, NOT in this message.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is one JSON-RPC message as produced by jsonrpc.EncodeMessage and
	// consumed by jsonrpc.DecodeMessage.
	Payload       []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_mcp_grpc_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_grpc_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_mcp_grpc_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_mcp_grpc_v1_transport_proto protoreflect.FileDescriptor

const file_mcp_grpc_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x1bmcp/grpc/v1/transport.proto\x12\vmcp.grpc.v1\"'\n" +
	"\x05Frame\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayloadJ\x04\b\x02\x10\x102E\n" +
	"\fMCPTransport\x125\n" +
	"\aConnect\x12\x12.mcp.grpc.v1.Frame\x1a\x12.mcp.grpc.v1.Frame(\x010\x01B0Z.github.com/P4ST4S/mcp-grpc/mcpgrpcv1;mcpgrpcv1b\x06proto3"

var (
	file_mcp_grpc_v1_transport_proto_rawDescOnce sync.Once
	file_mcp_grpc_v1_transport_proto_rawDescData []byte
)

func file_mcp_grpc_v1_transport_proto_rawDescGZIP() []byte {
	file_mcp_grpc_v1_transport_proto_rawDescOnce.Do(func() {
		file_mcp_grpc_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_grpc_v1_transport_proto_rawDesc), len(file_mcp_grpc_v1_transport_proto_rawDesc)))
	})
	return file_mcp_grpc_v1_transport_proto_rawDescData
}

var file_mcp_grpc_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_grpc_v1_transport_proto_goTypes = []any{
	(*Frame)(nil), // 0: mcp.grpc.v1.Frame
}
var file_mcp_grpc_v1_transport_proto_depIdxs = []int32{
	0, // 0: mcp.grpc.v1.MCPTransport.Connect:input_type -> mcp.grpc.v1.Frame
	0, // 1: mcp.grpc.v1.MCPTransport.Connect:output_type -> mcp.grpc.v1.Frame
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_grpc_v1_transport_proto_init() }
func file_mcp_grpc_v1_transport_proto_init() {
	if File_mcp_grpc_v1_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_grpc_v1_transport_proto_rawDesc), len(file_mcp_grpc_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcp_grpc_v1_transport_proto_goTypes,
		DependencyIndexes: file_mcp_grpc_v1_transport_proto_depIdxs,
		MessageInfos:      file_mcp_grpc_v1_transport_proto_msgTypes,
	}.Build()
	File_mcp_grpc_v1_transport_proto = out.File
	file_mcp_grpc_v1_transport_proto_goTypes = nil
	file_mcp_grpc_v1_transport_proto_depIdxs = nil
}
